import logging
import functools
from datetime import datetime

import pytz
from apscheduler.schedulers.asyncio import AsyncIOScheduler

from config import REPORTS_GROUP_ID
from phrases import get_phrase
from awards import sunday_final_logic
from database import get_inactive_users
from ratings import get_rating_data

logger = logging.getLogger(__name__)


# ==============================================================================
# SAFE DECORATOR FOR SCHEDULED JOBS
# ==============================================================================

def safe_job(func):
    """
    Wrapper for APScheduler jobs.
    Ensures one failed job does not break the scheduler.
    """
    @functools.wraps(func)
    async def wrapper(*args, **kwargs):
        try:
            return await func(*args, **kwargs)
        except Exception as e:
            logger.error(
                f"[SCHEDULER] Error in job {func.__name__}: {e}",
                exc_info=True,
            )
    return wrapper


# ==============================================================================
# HELPERS
# ==============================================================================

async def build_top3_text() -> str:
    """
    Builds TOP-3 rating block for scheduled messages.
    Returns empty string if rating is unavailable.
    """
    try:
        data = await get_rating_data(0)
        if not data or "top" not in data:
            return ""

        top_list = data.get("top", [])
        if not top_list:
            return ""

        lines = ["", "🏆 *ТОП-3 ЗАРАЗ:*", ""]

        for i, player in enumerate(top_list[:3]):
            if i == 0:
                icon = "🥇"
            elif i == 1:
                icon = "🥈"
            else:
                icon = "🥉"

            nick = player.get("nick", "Unknown")
            hp = player.get("hp", 0)
            lines.append(f"{icon} {nick} — {hp} HP")

        return "\n".join(lines)

    except Exception as e:
        logger.error(f"[TASKS] Failed to build top-3 text: {e}", exc_info=True)
        return ""


# ==============================================================================
# SCHEDULED TASKS
# ==============================================================================

@safe_job
async def send_morning_motivation(bot) -> None:
    """08:00 Kyiv — morning motivation + top-3."""
    phrase = get_phrase("morning")
    top3 = await build_top3_text()
    text = phrase + top3
    await bot.send_message(chat_id=REPORTS_GROUP_ID, text=text, parse_mode="Markdown")
    logger.info("[TASKS] Morning motivation sent")


@safe_job
async def send_evening_motivation(bot) -> None:
    """21:00 Kyiv — evening motivation + top-3."""
    phrase = get_phrase("evening")
    top3 = await build_top3_text()
    text = phrase + top3
    await bot.send_message(chat_id=REPORTS_GROUP_ID, text=text, parse_mode="Markdown")
    logger.info("[TASKS] Evening motivation sent")


@safe_job
async def inactive_reminder(bot) -> None:
    """
    11:00 Kyiv every day — mention users inactive for 4+ days.
    List is generated by GAS.
    """
    inactive_list = await get_inactive_users()
    if not inactive_list:
        logger.info("[TASKS] Inactive reminder: everyone is active")
        return

    mentions = " ".join(inactive_list)
    text = (
        f"🚨 **РОЗДУПЛЯТОР ТУРБОТІМ** 🚨\n\n"
        f"{mentions}\n\n"
        f"Бро, ти де зник? Вже 4 дні тиші! "
        f"Повертайся в стрій, HP самі себе не зароблять! 🔥"
    )
    await bot.send_message(
        chat_id=REPORTS_GROUP_ID, text=text, parse_mode="Markdown"
    )
    logger.info(f"[TASKS] Inactive reminder triggered for {len(inactive_list)} users")


@safe_job
async def run_sunday_final(bot) -> None:
    """
    20:00 Kyiv every Sunday — weekly final.
    """
    logger.info("[TASKS] Sunday Final started...")
    await sunday_final_logic(bot)
    logger.info("[TASKS] Sunday Final finished.")


# ==============================================================================
# SCHEDULER SETUP
# ==============================================================================

def setup_scheduler(bot) -> AsyncIOScheduler:
    """
    Configures and starts APScheduler.
    Returns scheduler instance.
    """
    kyiv_tz = pytz.timezone("Europe/Kyiv")
    scheduler = AsyncIOScheduler(timezone=kyiv_tz)

    scheduler.add_job(
        send_morning_motivation, "cron", hour=8, minute=0, args=[bot]
    )
    scheduler.add_job(
        inactive_reminder, "cron", hour=11, minute=0, args=[bot]
    )
    scheduler.add_job(
        send_evening_motivation, "cron", hour=21, minute=0, args=[bot]
    )
    scheduler.add_job(
        run_sunday_final, "cron", day_of_week="sun", hour=20, minute=0, args=[bot]
    )

    scheduler.start()

    now_str = datetime.now(kyiv_tz).strftime("%H:%M:%S")
    logger.info(f"[TASKS] Scheduler started. Kyiv time: {now_str}")

    return scheduler